#include "topconn.ch"
#include "totvs.ch"
#include "tbiconn.ch"

/*/{Protheus.doc} u_TstVendedor3
Rotina para testar a classe VendedorClass
@author Gabriel Dantas
@since 17/07/2024
@version 1.0
/*/
Function u_TstVendedor3

    // Declaração de variáveis locais
    Local oVendedor := VendedorClass():new()
    Local cCodVendedor := "0001"
    Local cFilialVendedor := "99"


    // Testando o método create()
    oVendedor:create(cCodVendedor, cFilialVendedor)
    


Return
